version: "3.3"
services:    
  es1:
    build: .
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./snapshot1:/etc/snapshots
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"

### add additionall instances accordingly
#  es2:
#    build: .
#    volumes:
#      - ./esdata2:/usr/share/elasticsearch/data
#      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./snapshot2:/etc/snapshots
#    environment:
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - discovery.type=single-node
#    ports:
#      - "9301:9300"
#      - "9201:9200"

volumes:
  esdata1:
  #  esdata2:
